
---
title: "BIOL 5380"
---

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">


Welcome to BIOL 5380, Topics in Biomechanics!!! 

In BIOL 5380, we'll explore how physical principles constrain or contribute to biological processes, including movement, feeding, and transport. By drawing on physics and mechanical engineering, the educational goal of the course is to understand how organisms swim, fly, walk, consume resources, and respond to moving fluids as well as how their size affects the design of mechanical systems. Central to all these topics will be investigations of how biological materials (e.g., wood, muscle, bone, skin, etc.) influence the mechanical behavior of complex life forms. The course will prepare students for more in-depth explorations of other related disciplines including biomechanical engineering, ergonomics, orthopedics, kinesiology, and sports medicine.

A second goal of the course is to engage in the scientific process, that is:

learn $\rightarrow$ hypothesize $\rightarrow$ experiment $\rightarrow$ analyze $\rightarrow$ communicate


Pursuant to this, you'll engage in class projects that involve reading primary literature, data collection and analysis, and the presentation of this work to your peers. These projects will require patience, resilience, and most of all, curiosity (all qualities a scientist---and especially a biomechanist---will find very handy in their career!). You'll find that one very important aspect of the course is challenging you to be proficient with technology (i.e., software, hardware, instruments, etc.). Biomechanics is a very, **very** technical field. Please rest assured, if you summon your curiosity, patience, and resilience, you'll find this part of the course very rewarding.

# Course Deets

**Delivery:**  In-person lectures Tuesday and some Thursdays at 10:30 in Higgins Hall 225. Asynchronous lab projects launched on Thursdays with a synchronous Zoom meeting.

For those who can't make it to class, we'll be [Zooming](https://bccte.zoom.us/j/9533582156) 

<!-- and [recording lectures](https://bostoncollege.instructure.com/courses/1615104/external_tools/109499). -->

**Instructor:** [Christopher P. Kenaley (Prof. K)](https://kenaleylab.com)


<a class="far fa-envelope fa-1x" style="color:#D3D8DD"></a> kenaley [ahhhht] bc.edu


**Course TA:** Trevor Cameron

<a class="far fa-envelope fa-1x" style="color:#D3D8DD"></a> camerotr [ahhhht] bc.edu



**office hours with Prof. Kenaley:** By appointment, in person or over Zoom [at this link](https://bccte.zoom.us/j/9533582156)


**office hours with Trevor:** Wednesdays, 1:00-3:00 in person (Higgins 535) and Fridays 1:00-3:00 over Zoom [at this link](https://bccte.zoom.us/j/6907654693?pwd=TU5YelZnS1VLUnNJMnVSWFkwV3RUdz09)

# Course Materials

## Readings, Tools, etc.

**Recommended Textbook:** Vogel, S. 2013. [*Comparative Biomechanics: Life's Physical World*.](https://www.amazon.com/Comparative-Biomechanics-Lifes-Physical-Second/dp/0691155666#customerReviews) 2nd ed. Princeton University Press. 

**Additional readings and lecture files:** Required readings drawn from the primary literature are available through the class schedule on the course site. They should be read before the class for which they are assigned. 

**Technical requirements:**  Completing your assignments will require proficiency with non-commercial software, including some amount of low-level programming. Early assignments in the course are meant to bring you up to speed; however, most students in the class will have to rely on their patience and curiosity to transfer these new skills to complete assignments. Prof. Kenaley promises you that scientific computing with free, but powerful software (e.g. R, imageJ, etc.) will be utterly liberating and rewarding! 

## GitHub Account

Why a [GitHub account](https://github.com/join)? GitHub is a handy place for those developing code and offers free hosting of websites produced and maintained from a desktop (that's how this site was constructed). Our site is under the ``class" repository (i.e., a space where code resides) within the organization [bcbiomech](https://github.com/bcbiomech) on GitHub. To access our organization and use the bcbiomech discussion page, you'll need an account. Once you have an account, I'll be able to add you to our [bcbiomech](https://github.com/bcbiomech) team and the class-wide team for discussion purposes.


# Canvas Support

You'll find nearly everything you need for BIOL 5380 here at this site; however, grades will be posted to our [class Canvas site](https://bostoncollege.instructure.com/courses/1615104). 


# Course Goals and Objectives

## Learning Goals
This course is structured around the use of physical, mathematical, and engineering concepts to explore a breadth of biological processes that span all scales of biological organization, from cells to ecosystems. The learning goals for BIOL 5380 are based upon the [Core Competencies](https://live-visionandchange.pantheonsite.io/wp-content/uploads/2011/03/Revised-Vision-and-Change-Final-Report.pdf) that were identified by the American Association for the Advancement of Science in their [Vision and Change in Undergraduate Biology Education initiative](https://live-visionandchange.pantheonsite.io/about-vc-unpacking-a-movement-2018/). They include the ability to:

  + Apply the process of science
  
  + Use quantitative reasoning
  
  + Use modeling and simulation
  
  + Tap into the interdisciplinary nature of science
  
  + Communicate and collaborate with other disciplines.

## Learning Objectives
Within the context of BIOL 5380, these goals can be articulated in the following specific learning objectives:

  + Develop interesting questions related to how structure relates to function within the integrated systems of organisms.
  
  + Integrate concepts across disciplines and beyond biology to answer questions in biomechanics.
  
  + Leverage quantitative skills---including modeling, simulations, and data visualization---to address questions in biomechanics.
  
  + Communicate answers to questions through clear and concise reports and presentation.
  
These objectives model the approach taken by a modern biomechanists and thus represent an experience that will prepare students for future work in this and related fields (e.g., orthopedics, sports medicine, physical therapy, bioengineering, etc.).

# Course Format

## Lectures

Lectures will be a relaxed experience meant to stimulate discussions around the major themes and concepts related to biomechanics. We have no exams or quizzes, but please expect a high level of engagement. That is, lectures will be more than Prof. Kenaley talking and students listening. Pauses for brief illustrative exercises and discussions between all of us will be common and an important part of the lecture experience. Lectures will be posted as PDF on our [schedule page](schedule.html).

## Labs
As a course-based research experience (i.e., an AE course), BIOL 5380 is meant to develop and hone research and quantitative skills related to biomechanics. Specifically, we'll leverage core concepts from lecture discussions to explore, quantify, and report on data collected with your own hands and eyes.   

To this end, you will participate in 5 asynchronous lab exercises (i.e., Mini-projects, "MPs") over the course of the semester. For each MP, you'll be led out with an MP project description, then perform experiments and collect data. After you've completed the experiments and analyzed your data, you'll be asked to synthesize and contextualize your results in a report. These reports---due on Wednesdays---should be short (<1000 words), contain relevant figures and table, and discuss the importance of the results. Each MP is worth up to 50 points toward your final grade.

Additional details for the MPs are available on our [Mini-Projects page](mini_projects.html).

<div class = "green">
<div class="row">
  <div class="col-sm-2"><a class="far fa-sticky-note fa-5x" style="color:#D3D8DD"></a> <!-- regular style --></div>
  <div class="col-sm-9">Because of the integrative and technical nature of this course, students will often feel adrift, unsure of how to proceed. This is by design and a model of how work in the multi-disciplinary field of biomechanics unfolds. Nonetheless, students may worry about their grade in the course and how to do well when challenges emerge at every turn. Fear not! For each assignment in the course (e.g.,project reports) student or team engagement and effort will be assessed just as much as how well objective questions have been answered. 
</div>
</div>
</div>
<br>

<!-- A course of this scope, focusing on so much that is technical, would be administered best in small groups, meeting mostly face-to-face. However, in the context of a global pandemic that has surged again in our corner of the world, I can't in good conscience summon us all to meet in cramped quarters for our lab exercises. Thus, for each lab meeting, we'll first convene over Zoom and, after an introduction to the MP topic, students will move on to perform experiments in pre-assigned teams independently. I will be available for additional discussion and problem solving over Zoom and face-to-face during arranged office hours.  -->

## Final Project

Toward the end of the course, you'll take on an independent, team-based project. The goal of this project is the use your quantitative skills and knowledge of biomechanical systems amassed while executing the MPs to address a new question of your choosing. The question should be new within the context of the course and the subjects of your research need not be human. However, consider the cooperability of the non-human subject when choosing what to study. You'll address your question in a longer ($\sim$5-page) report that should follow the same format and requirements of the MP reports, but with expanded content. The report is worth 100 points toward the final grade.

In addition to a report, you'll be tasked with synthesizing your project in a short, 10-minute research presentation. This presentation will be recorded by you and your team using Zoom and uploaded to a directory for Prof. Kenaley and your peers to view and critique.  The Final Project presentation is worth 50 points toward the final grade. Additional details for the FP are available on our [Final Project page](final_project.html).

## Discussion Board 

Each week on Tuesday, you will be asked to submit at least one question and answer another on our class [discussion board](https://github.com/orgs/bcbiomech/teams/biol5380_s23/discussions). This is hosted on GitHub, just like our course site, and will certainly be an important resource as you work through course material. When you post a question, you should:

  + Be polite and concise.
  + Ask a question that has not be asked before.
  + Post the question with a short descriptive title (e.g.., ``Problems with temp sensor wiring" )
  
When responding to a question, you should:

  + Be polite and concise
  + Provide unique feedback rather than a duplicated answer.
  
Feel free to post reactions (via the smiley-face icon above the text box), but this won't count as an answer.
  
A student is welcome to add another answer to a question that has already been answered as long as it expands upon the previous answers.  I'll be moderating and occasionally commenting myself, issuing periodic feedback. 

The discussion activities are worth 50 points toward the final grade. A complete discussion post includes both a question (2.5 points) and answer (2.5 points), for a subtotal of 5 points.  We have 11 discussions posts assigned (weeks 2 to 12), however, you're required to submit just 10. That is, we'll drop the lowest of 11 discussion scores and compile 10 of them for the final discussion grade.

# Course Assessment

Your grade will be based on five assignment components: Engagement in class, posting to our discussion board, 5 Mini-Project reports, and one independent Final Project report and presentation. 

***

### Grade Breakdown
-----------------------------------  ----------  --------------------    
                                                     **Points**            
     
Class participation and engagement                     50

Discussion Board                                      10x5 
  
Mini-Project Reports                                  5x50
 
Final Project Report                                   1x100
 
Final Project Presentation                              1x50
 
                                     **total**       **500**
-----------------------------------  ----------   --------------     

***

<br>

The class engagement portion of your grade will be calculated qualitatively. All 50 points are on the table, as long as you remain an active participant in class---asking questions, making relevant points, etc.



<div class = "green">
<div class="row">
  <div class="col-sm-2"><a class="far fa-sticky-note fa-5x" style="color:#939681"></a> <!-- regular style --></div>
  <div class="col-sm-9">Just a note . . . assessment for project reports will incorporate an evaluation of an individual's or team's effort and engagement in addition to more objective components (i.e., answers, conclusions, etc.). To do well, the formula is simple: students and their teams should remain persistent, ask for guidance, and make clear conclusions using the skills and tools they learn in the course.
</div>
</div>
</div>
<br>


# Responsibilities

## Expectations for Students

This technical course will require sublime concentration and focus. Therefore, we must be clear about our expectations of one another. 

  + You, the student, are responsible for reading and adhering to all aspects of the course syllabus as outlined here on this site.
  + You are responsible for organizing and completing all readings, discussions, exercises, and projects.
  + You are responsible for becoming familiar with course-related software (R, RStudio, Zoom, etc.).
  + You must be aware of your own progress in the course.
  + It is up to you to pursue help and guidance when you feel you need it.

## Expectations for the Instructor
  + I will challenge students intellectually to develop data analysis and experimental skills.
  + I will make expectations clear in the form of this site, syllabus, and course announcements made here and over email.
  + I will be consistent and quick in grading assignments.
  + I will be available to help and discuss topics during scheduled class time, arranged office hours, and on our class [discussion board](https://github.com/orgs/bcbiomech/teams/biol5380_s23/discussions).


# Accessibility

Boston College is committed to providing accommodations to students, faculty, staff and visitors with disabilities. Specific documentation from the appropriate office is required for students seeking accommodation in Woods College courses. Advanced notice and formal registration with the appropriate office is required to facilitate this process. There are two separate offices at BC that coordinate services for students with disabilities:

  + [The Connors Family Learning Center (CFLC)](http://www.bc.edu/libraries/help/tutoring.html) coordinates services for students with LD and ADHD.
  + [The Disabilities Services Office (DSO)](http://www.bc.edu/offices/dos/subsidiary_offices/disabilityservices.html) coordinates services for all other disabilities.

Find out more about BC’s commitment to accessibility at www.bc.edu/sites/accessibility.

# Academic Integrity

Students in this course, as all others at BC, must produce original work and cite references appropriately. Failure to cite references is plagiarism. Academic dishonesty includes, but is not necessarily limited to, plagiarism, fabrication, facilitating academic dishonesty, cheating on exams or assignments, or submitting the same material or substantially similar material to meet the requirements of more than one course without seeking permission of all instructors concerned. Scholastic misconduct may also involve, but is not necessarily limited to, acts that violate the rights of other students, such as depriving another student of course materials or interfering with another student’s work. Please see the [Boston College policy on academic integrity](https://www.bc.edu/content/bc-web/academics/sites/university-catalog/policies-procedures.html#academic_integrity_policies) for more information.

# Email and Office Hours Policy

If you write Professor Kenaley with a question, he’ll try to get back to you within 24 hours. If you don’t receive a response, it’s likely because the answer to your question is available here or on our discussion site. Rather than write Prof. Kenaley with questions related to course mechanics and expectations, please post these in our [discussion board](https://github.com/orgs/bcbiomech/teams/biol5380_s23/discussions), It’s probably the case that others have the same questions.

Office hours can be arranged by appointment via email and will take place over Zoom. Office hours may involve more more than student or team, so please come equipped with poignant questions and expect that other students have questions as urgent as yours.



&nbsp;
<hr />
<p style="text-align: center;">Cobbled together by <a href="https://kenaleylab.com">Chris Kenaley</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>kenaley@bc.edu</em></span></p>



<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://github.com/ckenaley/" class="fab fa-github"></a>
</p>

&nbsp;
