
---
title: "Mini-Projects"
---

We'll engage in 5 team-based asynchronous lab exercises or Mini-projects that span 2-3 weeks of class. Teams will be assigned the first week of class.

Fridays are set aside for MP work, but you and your team can meet to complete MP work when it suits you. New MPs will be released on Fridays with an MP project description (see links above under and our [schedule](schedule.html) page). These project descriptions begin with some background, a survey of some of the important concepts from class that we'll invoke in the MP, and the question we'll seek to answer. From there, you'll move on to performing experiments or simulations and collect data to answer the MP's question.


# Report Guidelines

After you've completed the experiments for an MP, you'll be asked to analyze data and synthesize and contextualize your results in a report. The reports should be short (<1000 words), contain relevant figures and table, and be written in R Markdown. They are due on Wednesdays and should be uploaded to a directory specified in the MP description. The submission should include the markdown file (an .Rmd) and **all the data** associated with the analysis. Each MP is worth up to 50 points toward your final grade.

In the first MP, we'll explore how to analyze data using R and how to synthesize analysis and text into a reproducible Markdown document. The following must be included in your .Rmd. How to implement each of these requirements will be discussed in MP1. 

  1. A YAML header that specifies the author, title, date, output, and bibliography file. 
  2. The following section headers that organize your text and includes 4-5 short relevant sentences:
      + Introduction: Include a brief background to the project (why are we studying this anyway?), what the main questions is, and how this question will be answered.
      + Methods: Briefly outline the specifics of how the question will be answered.
      + Results: Briefly summarize the results.
      + Discussion: Briefly discuss the importance of the results (i.e., how they relate to the main question and the field in a broader context).
      + Author Contributions: Briefly state the contributions made by each team member to the project.
      + References: Populate a bibliography section that includes the works cited in the text.
  3. At least 1 relevant figure.
  4. All the code used in analysis and that produces figures. This should be included as code chunks.
  5. Citations to at least 2 relevant peer-reviewed papers.
  

# Rubric

The following rubric describes how each MP report will be evaluated. 

 |Component| **Spot On** |  **Pretty Good** | **Needs Work**  
|--------|-------- |-------- |--------
| Tasks and Outputs | Completes all tasks fully; submits all required outputs and materials (including data) on time  <br>**(10 pts)** | Completes a majority but not all tasks fully; submission meets the deadline  <br>**(6 pts)** | Completes few required tasks or submits few required materials; submission misses the deadline <br>**(2 pts)**
| Effort and Engagement | Individual or team asks questions or seeks help regularly <br>**(10 pts)**|  Individual or team asks questions or seek help sometimes, but not regularly <br>**(6 pts)**  |  Individual or team does not seem help <br>**(2 pts)**
| Report Format | Report contains all the appropriate headings and components (including a bibliography) <br>**(5 pts)**|  Report contains most of the appropriate headings and components (including a bibliography) <br>**(3 pts)** |  Report contains few of the appropriate headings and components <br>**(1 pt)**
| Analysis and Code | Report contains concisely written code chunks within the results or methods sections that produce the appropriate analyses, figures, and/or tables <br>**(10 pts)**|  One or a few code chunks are unneeded or produce analyses, figures, and/or tables not directly related to the project goals <br>**(6 pts)**| No code chunks contained in report or all code chunks are unneeded or produce analyses, figures, and/or tables not directly related to the project goals <br>**(2 pts)** 
| Graphics and Tables | Figures, tables, and images are clear, add much to the results in analysis, and have concise but descriptive captions <br>**(5 pts)**|   One or a few figures, tables, and images are unneeded or inappropriate or they lack captions that are concise or descriptive  <br>**(3 pts)**|  Few figures, tables, and images are unneeded or inappropriate <br>**(1 pt)**
| Writing and Style | The writing is concise, clear, avoids passive constructions, and is in the past tense; grammar is appropriate <br>**(5 pts)**|   The writing is unclear or rambling in spots or uses passive constructions and future tense; grammar is shaky in spots <br>**(3 pts)** |   The writing is unclear, and/or uses passive constructions or future tense throughout; grammar is shaky for the most part <br>**(1 pt)**
| Sources and References | Statements of scientific findings and fact are supported by references; references are contained in a BibTex bibliography and inserted with `@` tags.  <br>**(5 pts)**| Some statements of scientific findings and fact are not supported by references; some references are not contained in a BibTex bibliography or inserted with `@` tags <br>**(3 pts)** |   Most statements of scientific findings and fact are not supported by references; references are not contained in a ibex bibliography nor inserted with `@` tags <br>**(1 pt)**
||||

# Writing Advice

Students often find writing such reports---which resemble scientific manuscripts---difficult, specifically how to formulate the report and what to include in each section. Although the format and structure of our MPs are outlined in detail above, some additional advice may help. The very prestigious Nature publishing group has released a series of articles on their "Scitable" site devoted to writing in science. You may find [this article](https://www.nature.com/scitable/ebooks/english-communication-for-scientists-14053993/118519636#bookContentViewAreaDivID) helpful in writing your MP reports.

In addition to the structural requirements of including important sections and relevant text and figures, the writing must be clear and free of distracting usage errors and spelling mistakes. Here's some [writing advice](Common_mistakes.pdf) you might find helpful, complements of Prof. Kenaley's graduate school advisor.